POST http://127.0.0.1:3000/movies/create_multiple
content-type: application/json

{
  "user_id": 1,
  "movie_data": [
    {
      "director": "Frances Herbert",
      "title": "Dune 8"
    },
    {
      "director": "Frances Herbert",
      "title": "Dune 9"
    }
  ]
}